// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.vardb.hcv.resources;

import java.lang.Integer;
import java.lang.String;

privileged aspect Pathogen_Roo_JavaBean {
    
    public String Pathogen.getIdentifier() {
        return this.identifier;
    }
    
    public void Pathogen.setIdentifier(String identifier) {
        this.identifier = identifier;
    }
    
    public Integer Pathogen.getTaxid() {
        return this.taxid;
    }
    
    public void Pathogen.setTaxid(Integer taxid) {
        this.taxid = taxid;
    }
    
    public String Pathogen.getName() {
        return this.name;
    }
    
    public void Pathogen.setName(String name) {
        this.name = name;
    }
    
    public String Pathogen.getDescription() {
        return this.description;
    }
    
    public void Pathogen.setDescription(String description) {
        this.description = description;
    }
    
}
