// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.vardb.hcv.sequences;

import java.lang.String;

privileged aspect Sequence_Roo_JavaBean {
    
    public String Sequence.getAccession() {
        return this.accession;
    }
    
    public void Sequence.setAccession(String accession) {
        this.accession = accession;
    }
    
    public String Sequence.getSequence() {
        return this.sequence;
    }
    
    public void Sequence.setSequence(String sequence) {
        this.sequence = sequence;
    }
    
    public String Sequence.getGenotype() {
        return this.genotype;
    }
    
    public void Sequence.setGenotype(String genotype) {
        this.genotype = genotype;
    }
    
}
