/*global Ext */
(Ext.ux.vardb.Constants=function()
{	
	return {
		tooltips:
		{	
			accession: 'Unique accession number',
			tags: 'Clinical and user-defined tags',
			group: 'Group',
			description: 'Description/defline',
			taxon: 'NCBI taxonomy browser ID',
			gene: 'region of biological interest identified as a gene and for which a name has been assigned',
			sequence: 'Nucleotide sequence',
			ntlength: 'Length of nucleotide sequence',
			translation: 'Translated sequence',
			aalength: 'Length of protein sequence',		
			truncated: 'Not a full length coding sequence',
			pseudogene: 'Does not form a valid translated protein',
			rating: 'Sequence annotation quality',
			pathogen_dtype: 'Pathogen type',
			pathogen: 'Organism name',
			disease: 'Primary disease',
			family: 'Gene/protein family',
			ortholog: 'Ortholog group',
			subgroup: 'Gene family subgroup',
			country: 'locality of isolation of the sequenced organism indicated in terms of political names for nations, oceans or seas, followed by regions and localities',
			subregion: 'Sub region of collection site',
			ref: 'PubMed reference',		
			isolate: 'individual isolate from which the sequence was obtained',
			isolation_source: 'describes the physical, environmental and/or local geographical source of the biological sample from which the sequence was derived',
			molwt: 'Molecular weight',
			segment: 'Name of viral or phage segment sequenced',
			serotype: 'Serological variety of a species characterized by its antigenic properties',
			serogroup: 'Serological group of a species characterized by its antigenic properties',
			serovar: 'serological variety of a species characterized by its antigenic properties',
			hsubtype: 'Virus subtype',
			host: 'natural (as opposed to laboratory) host to the organism from which sequenced molecule was obtained',
			lab_host: 'Scientific name of the laboratory host used to propagate the source organism from the sequenced molecule was obtained',
			specific_host: 'Specific host',
			plasmid: 'name of naturally occurring plasmid from which the sequence was obtained',
			codedby: 'Gene coding this product',
			oldid: 'Old accession or identifier',
			natype: 'Nucleic acid type',
			clone: 'Clone used in sequencing',
			location: 'Location on chromosome',		
			locus_tag: 'Gene locus identifier',
			product: 'Name of the product associated with the feature',
			uniprot: 'UniProt identifier',
			udate: 'Entry date',		
			domains: 'Pfam domain architecture',
			method: 'Domain detection method',
			model: 'Pfam model',
			score: 'Pfam model score',
			evalue: 'Pfam model E-value score',
			resolution: 'Resolution (Angstroms)',
			numhsps: 'Number of high scoring pairs',
			hitevalue: 'E-value for first high-scoring pair',
			hitbitscore: 'Bit score for first high-scoring pair',
			hitlength: 'Length of BLAST hit'
		}
	};
}());